/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Bar: typeof import('./src/components/Bar.vue')['default']
    MdiArchiveArrowDownOutline: typeof import('~icons/mdi/archive-arrow-down-outline')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MdiMenuClose: typeof import('~icons/mdi/menu-close')['default']
    MdiPencilOutline: typeof import('~icons/mdi/pencil-outline')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
