/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Bar: typeof import('./src/components/Bar.vue')['default']
    MdiArchiveArrowDownOutline: typeof import('~icons/mdi/archive-arrow-down-outline')['default']
    MdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    MdiAudio: typeof import('~icons/mdi/audio')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    MdiImage: typeof import('~icons/mdi/image')['default']
    MdiMapMarker: typeof import('~icons/mdi/map-marker')['default']
    MdiMenu: typeof import('~icons/mdi/menu')['default']
    MdiMenuClose: typeof import('~icons/mdi/menu-close')['default']
    MdiMusic: typeof import('~icons/mdi/music')['default']
    MdiPencilOutline: typeof import('~icons/mdi/pencil-outline')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiSnowflake: typeof import('~icons/mdi/snowflake')['default']
    MdiVideo: typeof import('~icons/mdi/video')['default']
    MdiWeatherCloudy: typeof import('~icons/mdi/weather-cloudy')['default']
    MdiWeatherPartlyCloudy: typeof import('~icons/mdi/weather-partly-cloudy')['default']
    MdiWeatherRainy: typeof import('~icons/mdi/weather-rainy')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
